Update to 24.2 WIP (#89)
* Update memcpy

The type parameter for the memcpy function is now automatically inferred. This means that calls to memcpy of the form memcpy[Dtype.xyz](...) will no longer work and the user would have to change the code to memcpy(...).

* Update simd_load to load

As per The simd_load(), simd_store(), aligned_simd_load(), and aligned_simd_store() methods on DTypePointer, Buffer, and NDBuffer have been merged into a more expressive set of load() and store() methods with keyword-only width and alignment parameters:

* Update llama2.mojo

* DynamicVector -> List

DynamicVector has been renamed to List, and has moved from the collections.vector module to the collections.list module. I

* Update StaticTuple

StaticTuple parameter order has changed to StaticTuple[type, size] for consistency with SIMD and similar collection types.

* update width and push_back

List.push_back() has been removed. Please use the append() function instead.

* remove workaround

_steal_ptr

* rename nelts to width

* align with width name exposed

* Fix various store items

* fix argument

: error: invalid call to 'rand': missing 1 required positional argument: 'size'
    var r = rand[DType.float32](1)

* fix: expected ']' for parameter list

expected ']' for parameter list
    fn load[width=width: Int](self, *indices: Int) -> SIMD[DType.float32, width]:

* fix store

* align with new version

requires a size and pointer declared
create new pointer following https://docs.modular.com/mojo/stdlib/random/random#rand

alloc(1) for 1 value?

* tbd None check

'None' does not implement the '__bool__' method

* Fix compatibility issues

* Add supported version

---------

Co-authored-by: Aydyn Tairov <den.tairov@gmail.com>